version: '3'

services:
  php:
    build:
      context: .
    ports:
      - "8001:80"
    environment:
      - XDEBUG_CONFIG=remote_host=192.168.1.9
      - PHP_XDEBUG_ENABLED=1
    volumes:
      - ./www:/var/www/html
