version: '3'

services:
  php:
    build:
      context: .
    ports:
      - "80:8080"
    environment:
      - XDEBUG_CONFIG=remote_host=192.168.1.9
      - PHP_XDEBUG_ENABLED=1
    volumes:
      - ./www:/var/www
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    command: php -S 0.0.0.0:8080 -t /var/www/expressive/public/
    user: 1000:1000